Update json serialization (#112)
* Update json serialization

- tuples were not handled correctly, they wouldn't recursively sanitize
- understand numpy arrays and numpy numbers

* lint

* install dev

* Support python 3.3

* Fine, just use an old numpy

* merge conflicts

* Fix install on platforms without `requests`

Can occur when you are installing via pip in a fresh virtualenv

```
$ pip install -e ".[dev]"
Obtaining file:///Users/patrick/dev/sigopt-python
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/patrick/dev/sigopt-python/setup.py", line 5, in <module>
        from sigopt.version import VERSION
      File "/Users/patrick/dev/sigopt-python/sigopt/__init__.py", line 1, in <module>
        from .interface import Connection
      File "/Users/patrick/dev/sigopt-python/sigopt/interface.py", line 20, in <module>
        from .requestor import Requestor, DEFAULT_API_URL
      File "/Users/patrick/dev/sigopt-python/sigopt/requestor.py", line 1, in <module>
        import requests
    ModuleNotFoundError: No module named 'requests'
```

@alexandraj777

* Use backported open

* disable 3.7 for now...

* lint